--- 
apiVersion: apps/v1
kind: Deployments
metadata: 
  name: externaldns
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: externaldns
rules: 
  - 
    apiGroups: 
      - ""
    resources: 
      - services
      - endpoints
      - pods
    verbs: 
      - get
      - watch
      - list
  - 
    apiGroups: 
      - extensions
      - networking.k8s.io
    resources: 
      - ingresses
    verbs: 
      - get
      - watch
      - list
  - 
    apiGroups: 
      - ""
    resources: 
      - nodes
    verbs: 
      - get
      - watch
      - list
spec: 
  selector: 
    matchLabels: 
      app: externaldns
  strategy: 
    type: Recreate
  template: 
    metadata: 
      labels: 
        app: externaldns
    spec: 
      containers: 
        - 
          args: 
            - "--source=service"
            - "--source=ingress"
            - "--domain-filter={{domain-filter}}"
            - "--provider={{provider}}"
          image: 
            ? 
              image: ~
            : ~
          name: externaldns
          volumeMounts: 
            - 
              mountPath: /etc/kubernetes
              name: azure-config-file
              readOnly: true
      serviceAccountName: externaldns
      volumes: 
        - 
          name: azure-config-file
          secret: 
            secretName: azure-config-file
subjects: 
  - 
    kind: ServiceAccount
    name: externaldns
    namespace: default
